LOAD DATA INFILE "customer.tbl" INTO TABLE `CUSTOMER` COLUMNS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n';
LOAD DATA INFILE "lineitem.tbl" INTO TABLE `LINEITEM` COLUMNS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n';
LOAD DATA INFILE "nation.tbl" INTO TABLE `NATION` COLUMNS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n';
LOAD DATA INFILE "orders.tbl" INTO TABLE `ORDERS` COLUMNS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n';
LOAD DATA INFILE "part.tbl" INTO TABLE `PART` COLUMNS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n';
LOAD DATA INFILE "partsupp.tbl" INTO TABLE `PARTSUPP` COLUMNS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n';
LOAD DATA INFILE "region.tbl" INTO TABLE `REGION` COLUMNS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n';
LOAD DATA INFILE "supplier.tbl" INTO TABLE `SUPPLIER` COLUMNS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n';
